FROM 8.12.0-alpine

LABEL "com.github.actions.name"="dependencies"
LABEL "com.github.actions.description"="resolve dependencies by npm install"
LABEL "com.github.actions.icon"="download"
LABEL "com.github.actions.color"="gray-dark"

LABEL "repository"="https://github.com/tkrplus/niwalab-mdblog"
LABEL "maintainer"="tkrplus <tkrplus@github.com>"

CMD ["echo", "hello world!"]
